[build]
  command = "ng build --configuration production"
  publish = "dist/canora/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[images]
remote_images = ["https://blogger.googleusercontent.com/img/.*"]
